services:
  db-postgres:
    image: postgres:16
    container_name: dbmvp
    profiles: [ "local" ]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mvp-pgadmin
    profiles: [ "local" ]
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db-postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mvp-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: mvp-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--api-port=3000"
    ports:
      - "3000:3000"
volumes:
  pgdata:
